import { boolean, integer, jsonb, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt'), updatedAt: timestamp('updatedAt') })
export const materials = pgTable('materials', { id: serial('id').primaryKey(), userId: text('userId').notNull(), filename: text('filename').notNull(), pathname: text('pathname').notNull(), mimeType: text('mime_type').notNull(), size: integer('size').notNull(), status: text('status').notNull().default('uploaded'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const quizQuestions = pgTable('quiz_questions', { id: serial('id').primaryKey(), userId: text('userId').notNull(), materialId: integer('material_id'), prompt: text('prompt').notNull(), options: jsonb('options').$type<string[]>().notNull(), answerIndex: integer('answer_index').notNull(), explanation: text('explanation'), competency: text('competency').notNull(), createdAt: timestamp('created_at').notNull().defaultNow() })
export const quizAttempts = pgTable('quiz_attempts', { id: serial('id').primaryKey(), userId: text('userId').notNull(), score: integer('score').notNull(), total: integer('total').notNull(), weakAreas: jsonb('weak_areas').$type<string[]>().notNull().default([]), feedback: text('feedback'), answeredQuestionIds: jsonb('answered_question_ids').$type<number[]>().notNull().default([]), createdAt: timestamp('created_at').notNull().defaultNow() })
export const learningProgress = pgTable('learning_progress', { id: serial('id').primaryKey(), userId: text('userId').notNull(), competency: text('competency').notNull(), progress: integer('progress').notNull().default(0), minutes: integer('minutes').notNull().default(0), updatedAt: timestamp('updated_at').notNull().defaultNow() })
